
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 05 04:00:32 ICT 2019
//----------------------------------------------------

package src;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 4;
  public static final int AND = 15;
  public static final int LT = 9;
  public static final int NE = 12;
  public static final int ELSE = 18;
  public static final int PLUS = 2;
  public static final int INT = 24;
  public static final int OR = 16;
  public static final int RPAREN = 8;
  public static final int SEMI = 22;
  public static final int WHILE = 19;
  public static final int IF = 17;
  public static final int LBRACKET = 20;
  public static final int LPAREN = 7;
  public static final int GT = 13;
  public static final int ID = 31;
  public static final int LE = 10;
  public static final int RBRACKET = 21;
  public static final int BOOLEAN = 32;
  public static final int FLOAT = 25;
  public static final int NUMBER = 29;
  public static final int EOF = 0;
  public static final int DIVIDE = 5;
  public static final int NEWLINE = 23;
  public static final int GE = 14;
  public static final int MINUS = 3;
  public static final int PRINT = 28;
  public static final int error = 1;
  public static final int ASSIGN = 6;
  public static final int EQ = 11;
  public static final int BOOL = 27;
  public static final int REAL = 30;
  public static final int DOUBLE = 26;
}

