
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 05 01:29:10 ICT 2019
//----------------------------------------------------

package src;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 4;
  public static final int LT = 9;
  public static final int NE = 12;
  public static final int ELSE = 16;
  public static final int PLUS = 2;
  public static final int INT = 22;
  public static final int RPAREN = 8;
  public static final int CHAR = 24;
  public static final int SEMI = 20;
  public static final int WHILE = 17;
  public static final int IF = 15;
  public static final int LBRACKET = 18;
  public static final int LPAREN = 7;
  public static final int GT = 13;
  public static final int ID = 29;
  public static final int LE = 10;
  public static final int RBRACKET = 19;
  public static final int BOOLEAN = 25;
  public static final int NUMBER = 26;
  public static final int EOF = 0;
  public static final int DIVIDE = 5;
  public static final int GE = 14;
  public static final int MINUS = 3;
  public static final int PRINT = 21;
  public static final int error = 1;
  public static final int ASSIGN = 6;
  public static final int EQ = 11;
  public static final int BOOL = 28;
  public static final int REAL = 27;
  public static final int DOUBLE = 23;
}

