
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 22 14:21:21 ICT 2019
//----------------------------------------------------

package src;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 3;
  public static final int DIVIDE = 5;
  public static final int NUMBER = 11;
  public static final int SEMI = 9;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int ID = 13;
  public static final int REAL = 12;
  public static final int ASSIGN = 6;
  public static final int error = 1;
  public static final int RPAREN = 8;
  public static final int TIMES = 4;
  public static final int NEWLINE = 10;
  public static final int LPAREN = 7;
}

